# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(a)
print(a.size)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
27
int32
3
(3, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
b = np.array([[1,0,0,0,0],[2,3,0,0,0],[4,5,6,0,0],[7,8,9,10,0],[11,12,13,14,15]])
print(b)
print(b.shape)

[[ 1  0  0  0  0]
 [ 2  3  0  0  0]
 [ 4  5  6  0  0]
 [ 7  8  9 10  0]
 [11 12 13 14 15]]
(5, 5)


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [22]:
def printcheckboard(no_of_rows_col): 
      
    print("Checkerboard pattern:") 
    x = np.zeros((no_of_rows_col, no_of_rows_col), dtype = int)  
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1
      
    for i in range(no_of_rows_col): 
        for j in range(no_of_rows_col): 
            print(x[i][j], end =" ")  
        print()  
  
  
no_of_rows_col = 11
printcheckboard(no_of_rows_col) 

Checkerboard pattern:
0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 


# 4. Normalize a 5x5 random matrix

In [95]:
c = np.random.random((5,5))
#c=np.array([[1,2,3],[3,4,5],[6,7,8]])
print("before normalization :  \n",c)
x= (c-c.min())/(c.max()-c.min())
print("after normalization : \n",x)


before normalization :  
 [[0.50326705 0.09592629 0.55346807 0.04705037 0.20488912]
 [0.26977482 0.81313536 0.31788652 0.6089035  0.44908204]
 [0.18106289 0.35005817 0.58402874 0.64941896 0.25867653]
 [0.92139694 0.6552598  0.57274678 0.5925022  0.15324837]
 [0.96042016 0.53177239 0.22251676 0.23209327 0.35614964]]
after normalization : 
 [[0.49948738 0.05351165 0.55444981 0.         0.17280926]
 [0.24384916 0.83874571 0.2965241  0.61514311 0.44016309]
 [0.14672318 0.33174713 0.58790905 0.65950133 0.23169823]
 [0.95727555 0.66589615 0.57555704 0.5971862  0.11627055]
 [1.         0.53069636 0.19210882 0.20259364 0.33841635]]


# 5.  How to find common values between two arrays?

In [42]:
a1 = np.array([1,2,4,3,5,7,6])
a2 = np.array([1,4,7,6,8,9,10,44,32,45,102])
print("Array 1 = ",a1,"\n""Array 2 = ",a2)
x = np.intersect1d(a1,a2)
print(x)
print(x.shape)



Array 1 =  [1 2 4 3 5 7 6] 
Array 2 =  [  1   4   7   6   8   9  10  44  32  45 102]
[1 4 6 7]
(4,)


# 6.How to get the dates of yesterday, today and tomorrow?

In [50]:
y = np.datetime64('today','D') - np.timedelta64('1','D')
t = np.datetime64('today','D')
to = np.datetime64('today','D') + np.timedelta64('1','D')
print("yesterday",y,"\n""Today",t,"\n""Tomorrow",to)

yesterday 2020-07-24 
Today 2020-07-25 
Tomorrow 2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [77]:
a1 = np.random.randint(5,size=(2,3))
a2 = np.random.randint(5,size=(2,3))
print("Array 1 = \n",a1,"\n""Array 2 = \n",a2)
print("If result is true then the a1 and a2 are equal \n If result is false then the a1 and a2 are not equal")
x = np.allclose(a1,a2)
print("result = \t",x)


Array 1 = 
 [[4 2 1]
 [4 1 4]] 
Array 2 = 
 [[1 3 2]
 [4 3 4]]
If result is true then the a1 and a2 are equal 
 If result is false then the a1 and a2 are not equal
result = 	 False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [85]:
c = np.random.random((10,))
x=np.where(c==c.max(),0,c)
print(x)


[0.23866147 0.25549607 0.11535281 0.22345672 0.66402629 0.89202764
 0.23136628 0.02592582 0.         0.43657192]


# 9. How to print all the values of an array?

In [87]:
c = np.random.random((5,5))
print(c)

[[0.68003306 0.22002434 0.28813584 0.74989334 0.79775394]
 [0.87172477 0.34232663 0.57546131 0.3302762  0.85387098]
 [0.95124659 0.14425044 0.38198913 0.31657386 0.05519344]
 [0.27929213 0.11119608 0.28852077 0.92195239 0.92076822]
 [0.73887383 0.65760651 0.09455239 0.60991231 0.49434361]]


# 10.Subtract the mean of each row of a matrix

In [104]:

print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row :\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.00144624 0.43796386 0.52930479 0.08100439 0.39365544 0.818699
  0.68920857 0.6416419  0.11373335 0.31373406]
 [0.5080492  0.84985797 0.90900266 0.29318932 0.33443286 0.21408581
  0.65999953 0.09551864 0.85855314 0.3084251 ]
 [0.79323267 0.73711921 0.11477564 0.20380493 0.71498049 0.72487735
  0.2169282  0.81099966 0.11969547 0.37352281]
 [0.60798747 0.54669945 0.8183879  0.58362238 0.72094456 0.31630611
  0.32149121 0.48638317 0.69381245 0.22463161]
 [0.90367534 0.78776795 0.02611264 0.44182818 0.1254937  0.32421358
  0.10917427 0.16137614 0.06779785 0.19659195]]

Subtract the mean of each row :

[[-0.40059292  0.0359247   0.12726563 -0.32103477 -0.00838372  0.41665984
   0.28716941  0.23960274 -0.28830581 -0.0883051 ]
 [ 0.00493778  0.34674654  0.40589124 -0.20992211 -0.16867856 -0.28902562
   0.15688811 -0.40759278  0.35544171 -0.19468632]
 [ 0.31223902  0.25612556 -0.366218   -0.27718872  0.23398685  0.24388371
  -0.26406544  0.33000602 -0.36129817 -0.10747083]

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [7]:
import numpy as np

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[2. 3. 3. 2. 4. 4. 3. 4. 2. 3.]


# 12.How to get the diagonal of a dot product?

In [12]:
import numpy as np
A = np.random.randint(5,size=(3,3))
B = np.random.randint(5,size=(3,3))

print("Array 1 = \n",A,"\n""Array 2 = \n",B)

x=A.dot(B)
result = np.diag(x)
print(result)

Array 1 = 
 [[4 0 0]
 [1 1 0]
 [2 4 4]] 
Array 2 = 
 [[3 0 1]
 [3 0 3]
 [0 4 1]]
[12  0 18]


# 13.How to find the most frequent value in an array?

In [18]:
def most_freq(arr): 
    counter = 0
    num = arr[0] 
      
    for i in arr: 
        curr_freq = arr.count(i) 
        if(curr_freq> counter): 
            counter = curr_freq 
            num = i 
  
    return num 
  
arr = [1,2,3,3,3,4,5,6,7,8,9,9,9,9,6,6,6,6,6,6,7,7,7,7,7,7,7,8,9,9] 
print(most_freq(arr)) 

7


# 14.How to get the n largest values of an array

In [25]:
import numpy as np
x = np.arange(121)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120]
[120]


# 15.How to create a record array from a regular array?

In [29]:
import numpy as np
roll_no=np.array([1001,1002,1003,1004])
name=np.array(['Rahul','Goli','tapu','sonu'])
marks_in_math=np.array([60,78,65,98])
rec= np.core.records.fromarrays([roll_no, name, marks_in_math])
print(rec[0])
print(rec[1])
print(rec[2])

(1001, 'Rahul', 60)
(1002, 'Goli', 78)
(1003, 'tapu', 65)
